name       : strongswan
version    : 5.8.4
release    : 1
source     :
    - https://download.strongswan.org/strongswan-5.8.4.tar.gz : 8a33e2dbab03f64f09ca8917e2d6574d0c62690fed97c5a3b6cc88ad3229ee7e
license    : GPL-2.0-or-later
component  : network.clients
summary    : An Open Source IPsec-based VPN solution for Linux
description: |
    strongSwan is an Open Source IPsec-based VPN solution for Linux
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libnm)
    - iproute2
rundeps    :
    - iproute2
setup      : |
    %configure --sysconfdir=/etc \
               --prefix=/usr \
               --libexecdir=/usr/lib \
               --enable-openssl \
               --enable-curl \
               --enable-nm \
               --enable-bliss \
               --enable-agent \
               --enable-eap-gtc \
               --enable-eap-peap \
               --enable-eap-md5 \
               --enable-eap-mschapv2 \
               --enable-eap-identity
build      : |
    %make
install    : |
    %make_install
