name       : strongswan
version    : 5.9.11
release    : 9
source     :
    - https://download.strongswan.org/strongswan-5.9.11.tar.gz : c0a8160c4d2743d7b998af27a4f268d3ba14b7509c2fd29af96c73685feec0c7
license    : GPL-2.0-or-later
component  : network.clients
summary    : An Open Source IPsec-based VPN solution for Linux
description: |
    strongSwan is an Open Source IPsec-based VPN solution for Linux
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libnm)
    - iproute2
rundeps    :
    - iproute2
conflicts  :
    - libreswan
setup      : |
    %configure --sysconfdir=/etc \
               --prefix=/usr \
               --libexecdir=/usr/lib \
               --enable-openssl \
               --enable-curl \
               --enable-nm \
               --enable-bliss \
               --enable-agent \
               --enable-eap-gtc \
               --enable-eap-peap \
               --enable-eap-md5 \
               --enable-eap-mschapv2 \
               --enable-eap-identity
build      : |
    %make
install    : |
    %make_install
